### ISSUE TITLE
Review the documentation

### ISSUE THREAD

**Issue by danielnorio** [Bonitasoft-Community/widget_beartable#1]
Review the documentation to clarify the usage of css style and classes properties.
![capture](https://cloud.githubusercontent.com/assets/11405782/16811824/92dc7eea-4900-11e6-90ca-24c463095426.PNG)

Sorry, maybe it's clear for someone with more experience or to whom wrote the code, but to me it's not, as depends on bonita usage and widget implementation.

**Comment by pierre-yves-monnet** [comment]
Hello,
Sorry for the delay.

I explain more the documentation. The CSS class is to add a CSS class, but that imply that you define this class in a file, and then you load the class a as an ASSET in the UI Designer page.
It's nice if you do that : create you CSS file, and then load in all the different page.
If you want to change locally a style (set a background), this way to work is very long. Then, it's more easy to just add a style on the widget (like background-color: #323354)

That's why the Community widget in general define the two different properties.
Bonita Widget are more strict, and accept only CSS class.

Hope this help,
